### ISSUE TITLE
onPlayBackStarted method (& other methods from Player class)

### ISSUE THREAD

**Issue by Twilight0** [romanvm/kodistubs-generator#1]
As the title says, some methods are missing.

https://codedocs.xyz/xbmc/xbmc/class_x_b_m_c_addon_1_1xbmc_1_1_player.html

Sorry I had to report this here, because the other one does not have issues tab:
https://github.com/romanvm/Kodistubs

**Comment by romanvm** [comment]
Thank you for reporting this. BTW, I've restored issues tab for Kodistubs.
